spring:
  application:
    name: rest-service-6

  rabbitmq:
    host: rabbitmq

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
  cloud:
    stream:
      bindings:
        output:
          group: queue-group-1
          destination: my-rest-service-queue-1
          contentType: text/plain
          binder: rabbit
#        customoutput:
#          group: queue-1-group
#          destination: my-rest-service-queue-1
#          contentType: text/plain
#          binder: rabbit

server:
  port: 16006