# HTTP Server
server:
  port: 12345  # HTTP (Tomcat) port

spring:
  data:
    mongodb:
      host: station-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
      port: 27017