# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel2-service
  rabbitmq:
    host: rabbitmq
    listener:
      retry:
        enabled: false
        max-attempts: 1
    template:
      retry:
        enabled: false
        max-attempts: 1
  data:
    mongodb:
      host: ts-travel2-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    stream:
      bindings:
        output:
          group: ts-travel2
          destination: ts-travel2-return-travel2-detail-info-queue
          contentType: text/plain
          binder: rabbit
        input:
          group: ts-preserve-other
          destination: ts-preserve-other-search-travel2-detail-info-queue
          contentType: text/plain
          binder: rabbit

#  cloud:
#    stream:
#      bindings:
#        output:
#          group: ts-travel2
#          destination: ts-return-rebook-search-travel2-detail-info-queue
#          contentType: text/plain
#          binder: rabbit
#        input:
#          group: ts-rebook
#          destination: ts-rebook-search-travel2-detail-info-queue
#          contentType: text/plain
#          binder: rabbit