spring:
  application:
    name: rest-service-4
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
    timeout: 6

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 16004