# HTTP Server
server:
  port: 18673  # HTTP (Tomcat) port

spring:
  data:
    mongodb:
      host: ts-inside-payment-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017