spring:
  data:
    mongodb:
      host: mongo-local
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: jichao
      port: 27017

# HTTP Server
server:
  port: 12342  # HTTP (Tomcat) port