version: '3'
services:

  rest-service:
    image: 10.141.212.25:5555/my-rest-service
    restart: always
    ports:
      - 15000:15000
    deploy:
      replicas: 3

  rest-client:
    image: 10.141.212.25:5555/my-rest-client
    restart: always
    ports:
      - 15001:15001
    deploy:
      replicas: 3