version: '3'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - my-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - my-network


  ts-ui-dashboard:
    build: ts-ui-dashboard
    image: ts/ts-ui-dashboard
    restart: always
    ports:
      - 80:8080
    networks:
      - my-network

  ts-account-mongo:
    image: mongo
    networks:
      - my-network

  ts-sso-service:
    build: ts-sso-service
    image: ts/ts-sso-service
    restart: always
    ports:
      - 12349:12349
    networks:
      - my-network

  ts-contacts-service:
    build: ts-contacts-service
    image: ts/ts-contacts-service
    restart: always
    ports:
      - 12347:12347
    networks:
      - my-network
#    depends_on:
#      - linkerd-contacts

  ts-contacts-mongo:
      image: mongo
      networks:
        - my-network

  ts-admin-basic-info-service:
        build: ts-admin-basic-info-service
        image: ts/ts-admin-basic-info-service
        restart: always
        ports:
          - 18767:18767
        networks:
          - my-network
        depends_on:
          - linkerd-admin-basic-info

  linkerd-admin-basic-info:
      image: buoyantio/linkerd:1.3.2
      ports:
        - 9990:9990
        - 8071:8071
        - 8070:8070
      volumes:
        - ./linkerd/linkerd_config/linkerd-admin-basic-info.yml:/io.buoyant/linkerd/linkerd-admin-basic-info.yml:ro
        - ./linkerd/disco:/io.buoyant/disco:ro
      command: >
        - "/io.buoyant/linkerd/linkerd-admin-basic-info.yml"

  linkerd:
      image: buoyantio/linkerd:1.3.2
      ports:
      - 4140:4140 # expose for testing only
      - 9990:9990
      volumes:
      - ./linkerd.yml:/io.buoyant/linkerd/config.yml:ro
      command:
      - "/io.buoyant/linkerd/config.yml"

#  linkerd-contacts:
#      image: buoyantio/linkerd:1.3.2
#      container_name: linkerd-contacts
#      ports:
#        - 8072:8072
#        - 9991:9991
#      volumes:
#        - ./linkerd/linkerd_config/linkerd-contacts.yml:/io.buoyant/linkerd/linkerd-contacts.yml:ro
#        - ./linkerd/disco:/io.buoyant/disco:ro
#      command: >
#        - "/io.buoyant/linkerd/linkerd-contacts.yml"


networks:
    my-network:
      # driver: overlay
      driver: bridge





