version: '3'
services:

  ts-ui-dashboard:
    build: ts-ui-dashboard
    image: ts/ts-ui-dashboard
    restart: always
    ports:
      - 80:8080

  ts-login-service:
    build: ts-login-service
    image: ts/ts-login-service
    restart: always
    ports:
      - 12342:12342

  ts-account-mongo:
    image: mongo


  ts-register-service:
    build: ts-register-service
    image: ts/ts-register-service
    restart: always
    ports:
      - 12344:12344

  ts-register-mongo:
    image: mongo


  ts-sso-service:
    build: ts-sso-service
    image: ts/ts-sso-service
    restart: always
    ports:
      - 12349:12349


  ts-verification-code-service:
    build: ts-verification-code-service
    image: ts/ts-verification-code-service
    restart: always
    ports:
      - 15678:15678

  ts-contacts-service:
    build: ts-contacts-service
    image: ts/ts-contacts-service
    restart: always
    ports:
      - 12347:12347

  ts-contacts-mongo:
      image: mongo

  ts-order-service:
    build: ts-order-service
    image: ts/ts-order-service
    restart: always
    ports:
      - 12031:12031

  ts-order-mongo:
    image: mongo


  ts-config-service:
    build: ts-config-service
    image: ts/ts-config-service
    restart: always
    ports:
      - 15679:15679

  ts-config-mongo:
    image: mongo

  ts-station-service:
    build: ts-station-service
    image: ts/ts-station-service
    restart: always
    ports:
      - 12345:12345

  ts-station-mongo:
    image: mongo

  ts-train-service:
    build: ts-train-service
    image: ts/ts-train-service
    restart: always
    ports:
      - 14567:14567

  ts-train-mongo:
    image: mongo

  ts-travel-service:
    build: ts-travel-service
    image: ts/ts-travel-service
    restart: always
    ports:
      - 12346:12346

  ts-travel-mongo:
    image: mongo

  ts-travel2-service:
      build: ts-travel2-service
      image: ts/ts-travel2-service
      restart: always
      ports:
        - 16346:16346

  ts-travel2-mongo:
      image: mongo

  ts-preserve-service:
    build: ts-preserve-service
    image: ts/ts-preserve-service
    restart: always
    ports:
       - 14568:14568

  ts-basic-service:
      build: ts-basic-service
      image: ts/ts-basic-service
      restart: always
      ports:
        - 15680:15680

  ts-ticketinfo-service:
        build: ts-ticketinfo-service
        image: ts/ts-ticketinfo-service
        restart: always
        ports:
          - 15681:15681
