spring:
  data:
    mongodb:
      host: order-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: order-db
      port: 27017

# HTTP Server
server:
  port: 12031  # HTTP (Tomcat) port

