apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rest-service-delay
spec:
  destination:
    name: rest-service-2
  httpFault:
    delay:
      percent: 100
      fixedDelay: 10s




