apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-service-2-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: 
        app: rest-service-2
    spec:     
      containers: 
      - name: rest-service-2
        image: 10.141.212.25:5555/rest-service-2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16002