spring:
  data:
    mongodb:
      host: config-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
      port: 27017

# HTTP Server
server:
  port: 15679  # HTTP (Tomcat) port