# HTTP Server
server:
  port: 15678  # HTTP (Tomcat) port


spring:

  application:
    name: ts-verification-code-service

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0

