server:
  port: 12347

spring:
  application:
    name: ts-contacts-service
  data:
    mongodb:
      host: ts-contacts-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

