# HTTP Server
server:
  port: 12032  # HTTP (Tomcat) port
  tomcat:
    #    max-threads: 6
        max-connections: 1
        accept-count: 1

spring:
  application:
    name: ts-order-other-service
  data:
    mongodb:
      host: ts-order-other-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
      port: 27017

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0