version: '2'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092


  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
    
  

  rest-service-6:
    build: rest-service-6
    image: my-service-cluster/rest-service-6
    # image: 10.141.212.25:5555/my-rest-service-6
    restart: always
    ports:
      - 16006:16006

  rest-service-5:
    build: rest-service-5
    image: my-service-cluster/rest-service-5
    # image: 10.141.212.25:5555/my-rest-service-5
    restart: always
    ports:
      - 16005:16005

  rest-service-4:
    build: rest-service-4
    image: my-service-cluster/rest-service-4
    # image: 10.141.212.25:5555/my-rest-service-4
    restart: always
    ports:
      - 16004:16004

  rest-service-3:
    build: rest-service-3
    image: my-service-cluster/rest-service-3
    # image: 10.141.212.25:5555/my-rest-service-3
    restart: always
    ports:
      - 16003:16003
    mem_limit: 300M
    memswap_limit: 800M

  rest-service-2:
    build: rest-service-2
    image: my-service-cluster/rest-service-2
    # image: 10.141.212.25:5555/my-rest-service-2
    restart: always
    ports:
      - 16002:16002
    mem_limit: 300M
    memswap_limit: 800M

  rest-service-1:
    build: rest-service-1
    image: my-service-cluster/rest-service-1
    # image: 10.141.212.25:5555/my-rest-service-1
    restart: always
    ports:
      - 16001:16001
      - 16101:16101
    command:
      java -Xmx200m -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=16101 -jar /app/rest-service-1-0.1.0.jar
    

  # compose v2 non-swarm mode
  rest-service-end:
    build: rest-service-end
    image: my-service-cluster/rest-service-end
    # image: 10.141.212.25:5555/my-rest-service-end
    restart: always
    ports:
      - 16000:16000
    mem_limit: 300M
    memswap_limit: 800M
    # mem_reservation: 100M


    # compose v3 swarm mode
    # rest-service-end:
    # build: rest-service-end
    # image: my-service-cluster/rest-service-end
    # # image: 10.141.212.25:5555/my-rest-service-end
    # restart: always
    # ports:
    #   - 16000:16000
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 600M
    #     reservations:
    #       cpus: '0.1'
    #       memory: 300M
    #   replicas: 6
    #   restart_policy:
    #     condition: on-failure





  
