version: '3'
services:

  rest-service-6:
    build: rest-service-6
    image: my-service-cluster/rest-service-6
    restart: always
    ports:
      - 16006:16006

  rest-service-5:
    build: rest-service-5
    image: my-service-cluster/rest-service-5
    restart: always
    ports:
      - 16005:16005

  rest-service-4:
    build: rest-service-4
    image: my-service-cluster/rest-service-4
    restart: always
    ports:
      - 16004:16004

  rest-service-3:
    build: rest-service-3
    image: my-service-cluster/rest-service-3
    restart: always
    ports:
      - 16003:16003

  rest-service-2:
    build: rest-service-2
    image: my-service-cluster/rest-service-2
    restart: always
    ports:
      - 16002:16002

  rest-service-1:
    build: rest-service-1
    image: my-service-cluster/rest-service-1
    restart: always
    ports:
      - 16001:16001

  rest-service-end:
    build: rest-service-end
    image: my-service-cluster/rest-service-end
    restart: always
    ports:
      - 16000:16000





  
