# HTTP Server
server:
  port: 15680  # HTTP (Tomcat) port

#spring:
#  data:
#    mongodb:
#      host: ts-ticketinfo-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
#      database: ts
#      port: 27017