# HTTP Server
server:
  port: 12346  # HTTP (Tomcat) port

spring:
  data:
    mongodb:
      host: ts-travel-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017