# HTTP Server
server:
  port: 12346  # HTTP (Tomcat) port

spring:
  data:
    mongodb:
      host: travel-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
      port: 27017