spring:
  application:
    name: ts-inside-payment-service

  server:
    port: 18673

  data:
    mongodb:
      host: ts-inside-payment-mongo
#     username: user
#     password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017