spring:
  data:
    mongodb:
      host: contacts-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: jichao
      port: 27017

# HTTP Server
server:
  port: 12347  # HTTP (Tomcat) port