spring:
  application:
    name: rest-service-end
    
  rabbitmq:
    host: rabbitmq
    listener:
      retry:
        enabled: false
        max-attempts: 1
    template:
      retry:
        enabled: false
        max-attempts: 1

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
  cloud:
    stream:
      bindings:
        input:
          group: queue-group-x
          destination: my-rest-service-queue-x
          contentType: text/plain
          binder: rabbit

server:
  port: 16000