spring:
  application:
    name: rest-service-5

  rabbitmq:
    host: rabbitmq
    listener:
      retry:
        enabled: false
        max-attempts: 1
    template:
      retry:
        enabled: false
        max-attempts: 1

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
  cloud:
    stream:
      bindings:
        output:
          group: queue-group-2
          destination: my-rest-service-queue-2
          contentType: text/plain
          binder: rabbit
#        customoutput:
#          group: queue-1-group
#          destination: my-rest-service-queue-1
#          contentType: text/plain
#          binder: rabbit

server:
  port: 16005