spring:
  application:
    name: rest-service-5

  rabbitmq:
    host: rabbitmq

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
  cloud:
    stream:
      bindings:
        input:
          group: queue-1-group
          destination: my-rest-service-queue-1
          contentType: text/plain
          binder: rabbit
#        custominput:
#          group: queue-1-group
#          destination: my-rest-service-queue-1
#          contentType: text/plain
#          binder: rabbit

server:
  port: 16005