# HTTP Server
server:
  port: 18886  # HTTP (Tomcat) port

spring:
  application:
    name: ts-rebook-service
  rabbitmq:
    host: rabbitmq
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    stream:
      bindings:
        input:
          destination: ts-rebook-queue
          contentType: text/plain
          binder: rabbit
