# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port

#spring:
#  data:
#    mongodb:
#      host: ts-ticketinfo-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
#      database: ts
#      port: 27017

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0